name: user_repository
description: "The repo that handles users"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Equatable
  equatable: ^2.0.5

  # firebase_auth
  firebase_auth: ^5.3.0

  # cloud_firestore
  cloud_firestore: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
